# Generated by Django 3.2.24 on 2024-04-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_parent_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.parent'),
            preserve_default=False,
        ),
    ]
