# Generated by Django 3.2.24 on 2024-03-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20240305_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby_vaccine',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
