# Generated by Django 3.2.24 on 2024-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_baby_vaccine_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='baby_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
