# Generated by Django 3.2.24 on 2024-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_parent_baby_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability_status',
            field=models.CharField(default='AVAILABLE', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
