# Generated by Django 3.2.24 on 2024-04-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20240420_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40)),
                ('document', models.FileField(upload_to='document')),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.baby_details')),
                ('vaccination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vaccination')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
