# Generated by Django 3.2.24 on 2024-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
