# Generated by Django 3.2.24 on 2024-03-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20240311_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='discription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
