# Generated by Django 3.2.24 on 2024-04-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20240423_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccineUpdationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='document')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parent')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vaccination')),
            ],
        ),
    ]
