# Generated by Django 3.2.24 on 2024-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20240423_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='Days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
