# Generated by Django 3.2.24 on 2024-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20240315_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='duration',
            new_name='Age',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='Dose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
