# Generated by Django 3.2.24 on 2024-04-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_vaccination_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='Days',
            new_name='days',
        ),
    ]
