# Generated by Django 3.2.24 on 2024-03-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20240315_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby_details',
            name='vaccination_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vaccination'),
        ),
    ]
